id = "zed-context-server"
name = "Zed Context Server"
version = "0.1.1"
schema_version = 1
authors = ["Your Name <your.email@example.com>"]
description = "A context server extension for Zed"
repository = "https://github.com/yourusername/zed-context-server"

[commands.git_info]
title = "Git Info"
description = "Get information about the current git repository"

[context_servers.zed-context-server]
name = "A Zed Context Server"
