id = "libsql-context-server"
name = "Libsql Context Server"
description = "Model Context Protocol Server for Libsql"
version = "0.1.0"
schema_version = 1
authors = ["Nicholas Quezada <nicholas.quezada@outlook.com>"]
repository = "https://github.com/nicholasq/libsql-context-server"

[context_servers.libsql-context-server]
name = "Libsql Context Server"
