id = "zed-context-server"
name = "Zed Git Context Server"
version = "0.1.1"
schema_version = 1
authors = ["Saoud Rizwan"]
description = "Git context server extension for Zed's AI assistant"
repository = "https://github.com/saoudrizwan/zed-context-server"

[commands.git_info]
title = "Git Info"
description = "Get information about the current git repository"

[context_servers.zed-context-server]
name = "Git Context Server"
description = "Provides Git repository context through MCP"
